# Generated by Django 3.2.7 on 2021-11-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Правильный ответ'),
        ),
        migrations.DeleteModel(
            name='CorrectAnswer',
        ),
    ]
