# Generated by Django 3.2.7 on 2021-10-25 12:16

from django.db import migrations, models
import django.db.models.deletion
import testing.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_member_phone'),
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='typeoftest',
            options={'verbose_name': 'Тип теста', 'verbose_name_plural': 'Тип тестов'},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_option',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='member',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_options',
        ),
        migrations.AddField(
            model_name='answer',
            name='meaning',
            field=models.CharField(max_length=256, verbose_name='Ответ к вопросу'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testing',
            name='description',
            field=models.CharField(blank=True, max_length=256, verbose_name='Описание теста'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='result',
            field=models.IntegerField(blank=True, validators=[testing.models.validate_result], verbose_name='Результат тестирования'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_res', to='testing.testing', verbose_name='Тесты'),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_option', models.JSONField(verbose_name='Вариант ответа')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.member', verbose_name='Пользователь')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователя',
                'ordering': ['pk'],
            },
        ),
    ]
