# Generated by Django 3.2.9 on 2021-12-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_alter_test_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='time_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ограничение по времени (в мин.)'),
        ),
    ]
