# Generated by Django 3.2.7 on 2021-10-26 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_auto_20211026_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_res', to='testing.testing', verbose_name='Тесты'),
        ),
    ]
