# Generated by Django 3.2.7 on 2021-10-26 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_alter_testresult_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_res', to='testing.testing', verbose_name='Тесты'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer_option',
            field=models.JSONField(verbose_name='Варианты ответа'),
        ),
    ]
