# Generated by Django 3.2.7 on 2021-11-10 05:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_militarycommissariat_specialization'),
        ('account', '0012_alter_member_phone'),
        ('testing', '0005_auto_20211026_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='meaning',
            field=models.CharField(max_length=256, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answers',
            field=models.JSONField(blank=True, verbose_name='Ответы'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.IntegerField(choices=[(1, 'Один вариант ответа'), (2, 'Несколько вариантов ответа')], verbose_name='Количество вариантов'),
        ),
        migrations.AlterField(
            model_name='question',
            name='wording',
            field=models.CharField(max_length=256, verbose_name='Формулировка'),
        ),
        migrations.RenameModel('Testing', 'Test'),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.test', verbose_name='Номер теста'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_res', to='testing.test', verbose_name='Тесты'),
        ),
    ]
