# Generated by Django 3.2.7 on 2021-11-10 05:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_militarycommissariat_specialization'),
        ('account', '0012_alter_member_phone'),
        ('testing', '0005_auto_20211026_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='meaning',
            field=models.CharField(max_length=256, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answers',
            field=models.JSONField(blank=True, verbose_name='Ответы'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.IntegerField(choices=[(1, 'Один вариант ответа'), (2, 'Несколько вариантов ответа')], verbose_name='Количество вариантов'),
        ),
        migrations.AlterField(
            model_name='question',
            name='wording',
            field=models.CharField(max_length=256, verbose_name='Формулировка'),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название теста')),
                ('time_limit', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ограничение по времени (в мин.)')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='Описание теста')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.member', verbose_name='Создатель теста')),
                ('directions', models.ManyToManyField(blank=True, to='application.Direction', verbose_name='Направления тестов')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.typeoftest', verbose_name='Тип теста')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'ordering': ['create_date'],
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.test', verbose_name='Номер теста'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_res', to='testing.test', verbose_name='Тесты'),
        ),
        migrations.DeleteModel(
            name='Testing',
        ),
    ]
