# Generated by Django 3.2.6 on 2021-11-10 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_auto_20211110_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='time_limit',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ограничение по времени (в мин.)'),
        ),
    ]
