# Generated by Django 3.2.7 on 2021-11-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionfieldapp',
            name='value',
            field=models.TextField(verbose_name='Значение дополнительного поля'),
        ),
    ]
