# Generated by Django 3.1.2 on 2021-08-25 09:22

import application.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionfield',
            options={'verbose_name': 'Кастомное поле', 'verbose_name_plural': 'Кастомные поля'},
        ),
        migrations.AlterModelOptions(
            name='additionfieldapp',
            options={'verbose_name': 'Значение кастомного поля', 'verbose_name_plural': 'Значения кастомных полей'},
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['create_date'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='applicationcompetencies',
            options={'verbose_name': 'Выбранная компетенция', 'verbose_name_plural': 'Выбранные компетенции'},
        ),
        migrations.AlterModelOptions(
            name='competence',
            options={'verbose_name': 'Компетенция', 'verbose_name_plural': 'Компетенции'},
        ),
        migrations.AlterModelOptions(
            name='direction',
            options={'ordering': ['name'], 'verbose_name': 'Направление', 'verbose_name_plural': 'Направления'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Образование', 'verbose_name_plural': 'Образование'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Вложение', 'verbose_name_plural': 'Вложения'},
        ),
        migrations.AlterField(
            model_name='application',
            name='scholarships',
            field=models.TextField(blank=True, null=True, verbose_name='Стипендии'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='parent_node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.competence'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_path',
            field=models.FileField(upload_to=application.models.user_directory_path, verbose_name='Путь к файлу'),
        ),
    ]
