# Generated by Django 3.2.7 on 2021-11-30 06:42

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_additionfieldapp_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='avg_score',
            field=models.FloatField(validators=[application.models.validate_avg_score], verbose_name='Средний балл'),
        ),
    ]
