# Generated by Django 3.2.6 on 2021-09-01 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20210830_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='birth_day',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='application',
            name='scientific_achievements',
            field=models.TextField(blank=True, help_text='Статьи ВАК, РИМС ...', verbose_name='Достижения'),
        ),
        migrations.AlterField(
            model_name='application',
            name='sporting_achievements',
            field=models.TextField(blank=True, help_text='Разряды ...', verbose_name='Спортивные достижения'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='directions',
            field=models.ManyToManyField(blank=True, to='application.Direction', verbose_name='Название направления'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='parent_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='application.competence', verbose_name='Компетенция-родитель'),
        ),
    ]
