# Generated by Django 3.1.2 on 2021-08-25 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20210825_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='parent_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.competence'),
        ),
    ]
