# Generated by Django 3.2.7 on 2021-09-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20210901_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='application',
            name='candidate_exams',
            field=models.TextField(blank=True, help_text='Экзамены на кандидатский минимум, ...', verbose_name='Кандидатские экзамены'),
        ),
        migrations.AlterField(
            model_name='application',
            name='ready_to_secret',
            field=models.BooleanField(default=False, help_text='Готовность получить уровень секретности', verbose_name='Готовность к секретности'),
        ),
        migrations.AlterField(
            model_name='application',
            name='scholarships',
            field=models.TextField(blank=True, help_text='Президентская стипендия, ...', verbose_name='Стипендии'),
        ),
    ]
