# Generated by Django 3.2.9 on 2022-03-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20220302_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='theme_of_diploma',
            field=models.CharField(max_length=256, verbose_name='Тема диплома'),
        ),
    ]
