# Generated by Django 3.2.6 on 2021-09-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20210902_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationcompetencies',
            name='level',
            field=models.IntegerField(choices=[(0, ''), (1, 'Базовый'), (2, 'Можешь писать программы'), (3, 'Бог')]),
        ),
    ]
