# Generated by Django 3.2.9 on 2022-06-16 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_application_suitable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='suitable',
            new_name='unsuitable',
        ),
    ]
