# Generated by Django 3.2.6 on 2021-09-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_applicationcompetencies_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Имя файла'),
        ),
    ]
