# Generated by Django 3.2.6 on 2021-09-10 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_role_role_name'),
        ('application', '0007_alter_file_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='draft_season',
            field=models.IntegerField(choices=[(1, 'Весна'), (2, 'Осень')], verbose_name='Сезон призыва'),
        ),
        migrations.AlterField(
            model_name='application',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='account.member', verbose_name='Пользователь'),
        ),
    ]
