# Generated by Django 3.2.6 on 2021-09-14 07:54

import application.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20210910_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='fullness',
            field=models.IntegerField(default=0, verbose_name='Процент заполненности'),
        ),
        migrations.AlterField(
            model_name='education',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='application.application', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='education',
            name='avg_score',
            field=models.FloatField(blank=True, validators=[application.models.validate_avg_score], verbose_name='Средний балл'),
        ),
    ]
