# Generated by Django 3.2.7 on 2021-09-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20210914_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='name_of_education_doc',
            field=models.CharField(blank=True, max_length=256, verbose_name='Наименование документа об образовании'),
        ),
        migrations.AlterField(
            model_name='application',
            name='candidate_exams',
            field=models.TextField(blank=True, help_text='Наличие оформленного соискательства ученой степени и сданных экзаменов кандидатского минимума', verbose_name='Кандидатские экзамены'),
        ),
        migrations.AlterField(
            model_name='application',
            name='hobby',
            field=models.TextField(blank=True, help_text='Увлечения и хобби', verbose_name='Хобби'),
        ),
        migrations.AlterField(
            model_name='application',
            name='ready_to_secret',
            field=models.BooleanField(default=False, help_text='Готовность гражданина к оформлению допуска к сведениям, содержащим государственную тайну, по 3 форме', verbose_name='Готовность к секретности'),
        ),
        migrations.AlterField(
            model_name='application',
            name='scholarships',
            field=models.TextField(blank=True, help_text='Наличие грантов, именных премий, именных стипендий и т.п.', verbose_name='Стипендии'),
        ),
        migrations.AlterField(
            model_name='application',
            name='scientific_achievements',
            field=models.TextField(blank=True, help_text='Участие в конкурсах, олимпиадах, издательской деятельности, научно-практические конференции, наличие патентов на изобретения, свидетельств о регистрации программ, свидетельств о рационализаторских предложениях и т.п.', verbose_name='Научные достижения'),
        ),
        migrations.AlterField(
            model_name='application',
            name='sporting_achievements',
            field=models.TextField(blank=True, help_text='Наличие спортивных достижений и разрядов', verbose_name='Спортивные достижения'),
        ),
    ]
