# Generated by Django 3.2.6 on 2021-09-15 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_role_role_name'),
        ('application', '0010_auto_20210914_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_final',
            field=models.BooleanField(default=False, verbose_name='Законченность анкеты'),
        ),
        migrations.CreateModel(
            name='ApplicationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Текст заметки')),
                ('affiliations', models.ManyToManyField(blank=True, to='account.Affiliation', verbose_name='Принадлежность')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.member', verbose_name='Автор заметки')),
            ],
        ),
    ]
