# Generated by Django 3.2.7 on 2021-09-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_universities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universities',
            options={'verbose_name': 'Университет', 'verbose_name_plural': 'Университеты'},
        ),
        migrations.AlterField(
            model_name='universities',
            name='rating_place',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рейтинговое место'),
        ),
    ]
