# Generated by Django 3.2.7 on 2021-09-16 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20210916_0936'),
        ('application', '0013_alter_applicationnote_affiliations'),
    ]

    operations = [
    ]
