# Generated by Django 3.2.6 on 2021-09-17 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_auto_20210917_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='a1',
        ),
        migrations.RemoveField(
            model_name='application',
            name='a2',
        ),
        migrations.RemoveField(
            model_name='application',
            name='a3',
        ),
        migrations.RemoveField(
            model_name='application',
            name='a4',
        ),
        migrations.RemoveField(
            model_name='application',
            name='a5',
        ),
        migrations.RemoveField(
            model_name='application',
            name='a6',
        ),
        migrations.RemoveField(
            model_name='application',
            name='a7',
        ),
        migrations.AddField(
            model_name='application',
            name='postgraduate_additional_direction',
            field=models.BooleanField(default=False, verbose_name='Наличие ученой степени по специальности, не соответствующей профилю научных исследований научной роты'),
        ),
        migrations.AddField(
            model_name='application',
            name='postgraduate_prior_direction',
            field=models.BooleanField(default=False, verbose_name='Наличие ученой степени по специальности, соответствующей профилю научных исследований научной роты'),
        ),
        migrations.CreateModel(
            name='ApplicationScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1', models.FloatField(blank=True, default=0.0, verbose_name='Оценка кандидата по критерию "Склонность к научной деятельности"')),
                ('a2', models.FloatField(blank=True, default=0.0, verbose_name='Оценка кандидата по критерию "Средний балл диплома о высшем образовании"')),
                ('a3', models.FloatField(blank=True, default=0.0, verbose_name='Оценка кандидата по критерию "Соответствие направления подготовки высшего образования кандидата профилю научных исследований,выполняемых соответствующей научной ротой"')),
                ('a4', models.FloatField(blank=True, default=0.0, verbose_name='Оценка кандидата по критерию "Результативность образовательной деятельности"')),
                ('a5', models.FloatField(blank=True, default=0.0, verbose_name='Оценка кандидата по критерию "Подготовка по программе аспирантуры и наличие ученой степени"')),
                ('a6', models.FloatField(blank=True, default=0.0, verbose_name='Оценка кандидата по критерию "Опыт работы по профилю научных исследований, выполняемых соответствующей научной ротой"')),
                ('a7', models.FloatField(blank=True, default=0.0, verbose_name='Оценка кандидата по критерию "Мотивация к военной службе"')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='application.application', verbose_name='Заявка')),
            ],
        ),
    ]
