# Generated by Django 3.2.6 on 2021-09-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_alter_application_military_grants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationscores',
            options={'verbose_name': 'Оценки кандидата', 'verbose_name_plural': 'Оценки кандидата'},
        ),
        migrations.AlterField(
            model_name='application',
            name='final_score',
            field=models.FloatField(default=0, verbose_name='Итоговая оценка заявки'),
        ),
    ]
