# Generated by Django 3.2.6 on 2021-09-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_auto_20210917_1506'),
        ('application', '0018_auto_20210917_1554'),
    ]

    operations = [
    ]
