# Generated by Django 3.2.6 on 2021-09-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_merge_0015_auto_20210917_1506_0018_auto_20210917_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='a1',
        ),
        migrations.RemoveField(
            model_name='application',
            name='a2',
        ),
        migrations.RemoveField(
            model_name='application',
            name='a3',
        ),
        migrations.RemoveField(
            model_name='application',
            name='a4',
        ),
        migrations.RemoveField(
            model_name='application',
            name='a5',
        ),
        migrations.RemoveField(
            model_name='application',
            name='a6',
        ),
        migrations.RemoveField(
            model_name='application',
            name='a7',
        ),
        migrations.AlterField(
            model_name='application',
            name='military_grants',
            field=models.BooleanField(default=False, verbose_name='Обладательгрантов по научным работам, имеющим прикладное значение для Минобороны России, которые подтверждены органами военного управления'),
        ),
        migrations.AlterField(
            model_name='applicationscores',
            name='a1',
            field=models.FloatField(default=0.0, verbose_name='Оценка кандидата по критерию "Склонность к научной деятельности"'),
        ),
        migrations.AlterField(
            model_name='applicationscores',
            name='a2',
            field=models.FloatField(default=0.0, verbose_name='Оценка кандидата по критерию "Средний балл диплома о высшем образовании"'),
        ),
        migrations.AlterField(
            model_name='applicationscores',
            name='a3',
            field=models.FloatField(default=0.0, verbose_name='Оценка кандидата по критерию "Соответствие направления подготовки высшего образования кандидата профилю научных исследований,выполняемых соответствующей научной ротой"'),
        ),
        migrations.AlterField(
            model_name='applicationscores',
            name='a4',
            field=models.FloatField(default=0.0, verbose_name='Оценка кандидата по критерию "Результативность образовательной деятельности"'),
        ),
        migrations.AlterField(
            model_name='applicationscores',
            name='a5',
            field=models.FloatField(default=0.0, verbose_name='Оценка кандидата по критерию "Подготовка по программе аспирантуры и наличие ученой степени"'),
        ),
        migrations.AlterField(
            model_name='applicationscores',
            name='a6',
            field=models.FloatField(default=0.0, verbose_name='Оценка кандидата по критерию "Опыт работы по профилю научных исследований, выполняемых соответствующей научной ротой"'),
        ),
        migrations.AlterField(
            model_name='applicationscores',
            name='a7',
            field=models.FloatField(default=0.0, verbose_name='Оценка кандидата по критерию "Мотивация к военной службе"'),
        ),
    ]
