# Generated by Django 3.2.7 on 2021-09-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_alter_application_directions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationcompetencies',
            name='level',
            field=models.IntegerField(choices=[(0, 'не владеете компетенцией'), (1, 'уровнень базовых знаний, лабораторных работ вузовского курса'), (2, 'уровнень, позволяющий принимать участие в реальных проектах, конкурсах и т.п.'), (3, 'уровнень, позволяющий давать обоснованные рекомендации по совершенствованию компетенции разработчикам данной компетенции')]),
        ),
    ]
