# Generated by Django 3.2.7 on 2021-10-04 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_alter_applicationcompetencies_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-end_year'], 'verbose_name': 'Образование', 'verbose_name_plural': 'Образование'},
        ),
        migrations.AlterField(
            model_name='applicationnote',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='application.application', verbose_name='Анкета'),
        ),
    ]
