# Generated by Django 3.2.6 on 2021-09-29 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_auto_20210929_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationnote',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='application.application', verbose_name='Анкета'),
        ),
    ]
