# Generated by Django 3.2.7 on 2021-10-04 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_auto_20211004_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionfield',
            name='directions',
        ),
        migrations.RemoveField(
            model_name='additionfieldapp',
            name='directions',
        ),
    ]
