# Generated by Django 3.2.7 on 2021-10-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_auto_20211004_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionfield',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
