# Generated by Django 3.2.7 on 2021-10-04 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_additionfield_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionfield',
            name='slug',
        ),
    ]
