# Generated by Django 3.2.7 on 2021-10-06 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_alter_applicationnote_application'),
        ('application', '0026_remove_additionfield_slug'),
    ]

    operations = [
    ]
