# Generated by Django 3.2.7 on 2021-10-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0027_merge_20211006_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilitaryCommissariat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название коммисариата')),
                ('subject', models.CharField(max_length=128, verbose_name='Субъект')),
                ('city', models.CharField(max_length=128, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Военный комиссариат',
                'verbose_name_plural': 'Военные комиссариаты',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название специальности')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
    ]
