# Generated by Django 3.2.6 on 2021-11-10 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_member_phone'),
        ('application', '0028_militarycommissariat_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationcompetencies',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_competence', to='application.application'),
        ),
        migrations.AlterField(
            model_name='applicationcompetencies',
            name='competence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competence_value', to='application.competence'),
        ),
        migrations.CreateModel(
            name='WorkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название рабочей группы')),
                ('description', models.TextField(blank=True, verbose_name='Описание рабочей группы')),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_group', to='account.affiliation', verbose_name='Принадлежность')),
            ],
            options={
                'verbose_name': 'Рабочая группа',
                'verbose_name_plural': 'Рабочие группы',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='work_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='application.workgroup', verbose_name='Рабочая группа'),
        ),
    ]
