# Generated by Django 3.2.7 on 2021-11-10 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0029_auto_20211101_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationcompetencies',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_competence', to='application.application'),
        ),
        migrations.AlterField(
            model_name='applicationcompetencies',
            name='competence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competence_value', to='application.competence'),
        ),
    ]
