# Generated by Django 3.2.6 on 2021-11-15 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0029_auto_20211110_1234'),
        ('application', '0030_auto_20211110_1125'),
    ]

    operations = [
    ]
