# Generated by Django 3.2.7 on 2021-11-17 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0031_auto_20211112_1452'),
        ('application', '0031_merge_0029_auto_20211110_1234_0030_auto_20211110_1125'),
    ]

    operations = [
    ]
