version: '3.8'
services:
  web:
    build: ./science_selection
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/science_selection/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=master_user
      - POSTGRES_PASSWORD=master_user
      - POSTGRES_DB=app_dev
volumes:
  postgres_data:
