# Generated by Django 3.2.7 on 2021-11-22 07:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, verbose_name='Токен')),
            ],
            options={
                'verbose_name': 'Ссылка активации',
                'verbose_name_plural': 'Ссылки активации',
            },
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(verbose_name='Номер роты')),
                ('platoon', models.IntegerField(verbose_name='Номер взвода')),
            ],
            options={
                'verbose_name': 'Принадлежность',
                'verbose_name_plural': 'Принадлежности',
                'ordering': ('company', 'platoon'),
            },
        ),
        migrations.CreateModel(
            name='BookingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название бронирования')),
            ],
            options={
                'verbose_name': 'Тип бронирования',
                'verbose_name_plural': 'Типы бронирования',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=32, verbose_name='Название роли')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, max_length=32, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона формата: +79998887766', regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('affiliations', models.ManyToManyField(blank=True, to='account.Affiliation', verbose_name='Принадлежность')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.role', verbose_name='Роль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='account.affiliation', verbose_name='Принадлежность')),
                ('booking_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.bookingtype', verbose_name='Тип бронирования')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.member', verbose_name='Ведущий отбор')),
                ('slave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='account.member', verbose_name='Кандидат')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
    ]
