# Generated by Django 3.1.2 on 2021-08-26 09:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, verbose_name='Токен')),
            ],
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(verbose_name='Номер роты')),
                ('platoon', models.IntegerField(verbose_name='Номер взвода')),
            ],
        ),
        migrations.CreateModel(
            name='BookingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название бронирования')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, max_length=32, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона формата: +99999999999.', regex='^\\+?\\d{6,11}$')], verbose_name='Телефон')),
                ('affiliations', models.ManyToManyField(blank=True, to='account.Affiliation', verbose_name='Принадлежность')),
                ('role', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.role', verbose_name='Роль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.affiliation', verbose_name='Принадлежность')),
                ('booking_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.bookingtype', verbose_name='Тип бронирования')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.member', verbose_name='Ведущий отбор')),
                ('slave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='account.member', verbose_name='Кандидат')),
            ],
        ),
    ]
