# Generated by Django 3.2.9 on 2022-02-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='father_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Отчество'),
        ),
    ]
