# Generated by Django 3.1.2 on 2021-08-26 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210826_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activationlink',
            options={'verbose_name': 'Ссылка активации', 'verbose_name_plural': 'Ссылки активации'},
        ),
        migrations.AlterModelOptions(
            name='affiliation',
            options={'verbose_name': 'Принадлежность', 'verbose_name_plural': 'Принадлежности'},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AlterModelOptions(
            name='bookingtype',
            options={'verbose_name': 'Тип бронирования', 'verbose_name_plural': 'Типы бронирования'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.role', verbose_name='Роль'),
        ),
    ]
