# Generated by Django 3.2.6 on 2021-08-30 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210830_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.role', verbose_name='Роль'),
        ),
    ]
