# Generated by Django 3.2.6 on 2021-08-30 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_member_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='affiliation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.affiliation', verbose_name='Принадлежность'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.bookingtype', verbose_name='Тип бронирования'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.role', verbose_name='Роль'),
        ),
    ]
