# Generated by Django 3.2.6 on 2021-08-30 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210830_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона формата: +99999999999.', regex='^\\+?\\d{11}|\\d{6}$')], verbose_name='Телефон'),
        ),
    ]
