# Generated by Django 3.2.6 on 2021-09-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_member_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(max_length=32, verbose_name='Название роли'),
        ),
    ]
