# Generated by Django 3.2.6 on 2021-09-28 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_affiliation_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='affiliation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='account.affiliation', verbose_name='Принадлежность'),
        ),
    ]
